import type { ConfigParameter, PolicyCitation } from './types';

/**
 * Every statutory threshold, timeline and citation used anywhere in PRAYOG.
 * Components read these; they never contain the numbers themselves.
 * A change here changes the product with no component edit.
 */

export const CITATIONS: readonly PolicyCitation[] = [
  {
    id: 'GFR-2017-173',
    short: 'GFR 2017, Rule 173(i)',
    full: 'General Financial Rules 2017, Rule 173(i) — relaxation of prior turnover and prior experience for startups recognised by the competent authority.',
    effectiveFrom: '2017-03-07',
  },
  {
    id: 'GFR-2017-166',
    short: 'GFR 2017, Rule 166',
    full: 'General Financial Rules 2017, Rule 166 — bid security and earnest money deposit exemption for recognised startups and micro and small enterprises.',
    effectiveFrom: '2017-03-07',
  },
  {
    id: 'PP-MSE-2012',
    short: 'Public Procurement Policy for MSEs 2012',
    full: 'Public Procurement Policy for Micro and Small Enterprises Order 2012 — reservation and price preference in public procurement.',
    effectiveFrom: '2012-04-01',
  },
  {
    id: 'DPIIT-2019-127',
    short: 'DPIIT Notification G.S.R. 127(E)',
    full: 'DPIIT Notification G.S.R. 127(E) — definition, recognition and validity period of an eligible startup entity.',
    effectiveFrom: '2019-02-19',
  },
  {
    id: 'DPDP-2023-S8',
    short: 'DPDP Act 2023, Section 8',
    full: 'Digital Personal Data Protection Act 2023, Section 8 — obligations of a data fiduciary, including purpose limitation, retention and security safeguards.',
    effectiveFrom: '2023-08-11',
  },
  {
    id: 'CERTIN-2022-DIR',
    short: 'CERT-In Directions 2022',
    full: 'CERT-In Directions under Section 70B(6) of the Information Technology Act 2000, dated 28 April 2022 — incident reporting within the stipulated window and log retention.',
    effectiveFrom: '2022-06-28',
  },
  {
    id: 'PRAYOG-SOP-4',
    short: 'PRAYOG programme SOP, clause 4',
    full: 'PRAYOG programme standard operating procedure, clause 4 — gate ownership, precondition testing and waiver authority.',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'PRAYOG-SOP-9',
    short: 'PRAYOG programme SOP, clause 9',
    full: 'PRAYOG programme standard operating procedure, clause 9 — milestone acceptance, payment ageing and permissible deductions.',
    effectiveFrom: '2026-01-01',
  },
  {
    id: 'PRAYOG-SOP-12',
    short: 'PRAYOG programme SOP, clause 12',
    full: 'PRAYOG programme standard operating procedure, clause 12 — independent validation, procurement readiness and pathway selection.',
    effectiveFrom: '2026-01-01',
  },
] as const;

export function citation(id: string): PolicyCitation {
  const found = CITATIONS.find((c) => c.id === id);
  if (!found) throw new Error(`Unknown policy citation: ${id}`);
  return found;
}

export function citationShort(id: string): string {
  return CITATIONS.find((c) => c.id === id)?.short ?? id;
}

/** The configuration ledger. /a/config renders this array and nothing else. */
export const CONFIG_PARAMETERS: readonly ConfigParameter[] = [
  {
    key: 'sla.gate.g0.days',
    group: 'sla',
    label: 'Gate 0 decision window',
    value: 10,
    unit: 'working days',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Time allowed to the department after a challenge draft is complete.',
  },
  {
    key: 'sla.gate.g1.days',
    group: 'sla',
    label: 'Gate 1 decision window',
    value: 7,
    unit: 'working days',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-04-01',
    changedBy: 'PMU · A. Deshmukh',
    previousValue: 10,
    note: 'Publication readiness review. Shortened after the 2025 programme review.',
  },
  {
    key: 'sla.gate.g2.days',
    group: 'sla',
    label: 'Gate 2 decision window',
    value: 14,
    unit: 'working days',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Eligibility screening and shortlisting after applications close.',
  },
  {
    key: 'sla.gate.g3.days',
    group: 'sla',
    label: 'Gate 3 decision window',
    value: 21,
    unit: 'working days',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Expert evaluation, panel consensus and award.',
  },
  {
    key: 'sla.gate.g4.days',
    group: 'sla',
    label: 'Gate 4 decision window',
    value: 7,
    unit: 'working days',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Mid-pilot continue or stop review.',
  },
  {
    key: 'sla.gate.g5.days',
    group: 'sla',
    label: 'Gate 5 decision window',
    value: 15,
    unit: 'working days',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Independent validation and pilot outcome decision.',
  },
  {
    key: 'sla.gate.g6.days',
    group: 'sla',
    label: 'Gate 6 decision window',
    value: 30,
    unit: 'working days',
    citation: 'PRAYOG-SOP-12',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Procurement pathway decision by the competent authority.',
  },
  {
    key: 'sla.clarification.days',
    group: 'sla',
    label: 'Clarification answer window',
    value: 5,
    unit: 'calendar days',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Department must answer a published clarification within this window.',
  },
  {
    key: 'sla.milestone.review.days',
    group: 'sla',
    label: 'Milestone evidence review window',
    value: 10,
    unit: 'calendar days',
    citation: 'PRAYOG-SOP-9',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'From evidence submission to an explicit accept, reject or revision decision.',
  },
  {
    key: 'sla.dueSoon.ratio',
    group: 'sla',
    label: 'Due-soon threshold',
    value: 0.3,
    unit: 'fraction of window remaining',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Below this fraction of the window a clock enters the due-soon state.',
  },
  {
    key: 'payment.milestone.limit.days',
    group: 'payment',
    label: 'Milestone payment limit',
    value: 30,
    unit: 'calendar days from acceptance',
    citation: 'PRAYOG-SOP-9',
    effectiveFrom: '2026-01-01',
    changedBy: 'Finance · K. Iyer',
    note: 'The payment ageing clock starts on acceptance and is measured against this limit.',
  },
  {
    key: 'payment.deduction.max.percent',
    group: 'payment',
    label: 'Maximum permissible deduction',
    value: 10,
    unit: 'percent of claim',
    citation: 'PRAYOG-SOP-9',
    effectiveFrom: '2026-01-01',
    changedBy: 'Finance · K. Iyer',
    note: 'A deduction beyond this requires a separate competent-authority order.',
  },
  {
    key: 'payment.bulkApprove.max',
    group: 'payment',
    label: 'Bulk approval batch size',
    value: 20,
    unit: 'claims',
    citation: 'PRAYOG-SOP-9',
    effectiveFrom: '2026-01-01',
    changedBy: 'Finance · K. Iyer',
    note: 'Only claims with no exception may be approved in bulk.',
  },
  {
    key: 'eligibility.startup.maxAgeYears',
    group: 'eligibility',
    label: 'Maximum entity age to qualify as a startup',
    value: 10,
    unit: 'years from incorporation',
    citation: 'DPIIT-2019-127',
    effectiveFrom: '2019-02-19',
    changedBy: 'Statute',
    previousValue: 7,
    note: 'Statutory. Changing this requires a notification, not a product change.',
  },
  {
    key: 'eligibility.startup.maxTurnoverCrore',
    group: 'eligibility',
    label: 'Maximum turnover to qualify as a startup',
    value: 100,
    unit: 'crore rupees in any financial year',
    citation: 'DPIIT-2019-127',
    effectiveFrom: '2019-02-19',
    changedBy: 'Statute',
    note: 'Statutory ceiling for recognition validity.',
  },
  {
    key: 'eligibility.relaxable',
    group: 'eligibility',
    label: 'Requirements that may be relaxed for recognised startups',
    value: 'Prior turnover and prior experience only',
    citation: 'GFR-2017-173',
    effectiveFrom: '2017-03-07',
    changedBy: 'Statute',
    note: 'Relief is limited to these two. Quality, technical, security, safety and performance requirements are never relaxed by rule.',
  },
  {
    key: 'evaluation.rationale.minChars',
    group: 'evaluation',
    label: 'Minimum evaluator rationale length',
    value: 40,
    unit: 'characters per criterion',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'A score without a written reason is not a defensible score.',
  },
  {
    key: 'evaluation.outlier.threshold',
    group: 'evaluation',
    label: 'Outlier flag threshold',
    value: 1.5,
    unit: 'points from the panel mean',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Beyond this deviation the panel chair may request a written rationale.',
  },
  {
    key: 'evaluation.minEvaluators',
    group: 'evaluation',
    label: 'Minimum evaluators per application',
    value: 3,
    unit: 'evaluators',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Gate 3 cannot clear with fewer completed, conflict-free scores.',
  },
  {
    key: 'gate.decision.reason.minChars',
    group: 'gate',
    label: 'Minimum gate decision reason length',
    value: 50,
    unit: 'characters',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Every gate decision is an auditable record and carries a written reason.',
  },
  {
    key: 'gate.waiver.authority',
    group: 'gate',
    label: 'Authority required to waive a precondition',
    value: 'Secretary or equivalent, one level above the gate owner',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'A waiver never clears the precondition. It is recorded as a separate exception.',
  },
  {
    key: 'pilot.maxDurationDays',
    group: 'pilot',
    label: 'Maximum pilot duration without re-approval',
    value: 180,
    unit: 'calendar days',
    citation: 'PRAYOG-SOP-4',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'A longer pilot needs a fresh gate 3 record.',
  },
  {
    key: 'pilot.milestone.maxCount',
    group: 'pilot',
    label: 'Maximum milestones in a pilot',
    value: 6,
    unit: 'milestones',
    citation: 'PRAYOG-SOP-9',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Keeps acceptance testing and payment ageing tractable.',
  },
  {
    key: 'pilot.overBudget.tolerance.percent',
    group: 'pilot',
    label: 'Application over-budget tolerance',
    value: 0,
    unit: 'percent above the published pilot budget',
    citation: 'PRAYOG-SOP-9',
    effectiveFrom: '2026-01-01',
    changedBy: 'Finance · K. Iyer',
    note: 'An over-budget proposal is warned and requires a written justification. It is not blocked.',
  },
  {
    key: 'data.production.approvalLevel',
    group: 'data',
    label: 'Approval required for production data access',
    value: 'Department data custodian and programme management unit, jointly',
    citation: 'DPDP-2023-S8',
    effectiveFrom: '2023-08-11',
    changedBy: 'Statute',
    note: 'Production access is a decision, never a toggle.',
  },
  {
    key: 'data.credential.maxDays',
    group: 'data',
    label: 'Maximum sandbox credential validity',
    value: 90,
    unit: 'calendar days',
    citation: 'CERTIN-2022-DIR',
    effectiveFrom: '2022-06-28',
    changedBy: 'Statute',
    note: 'Credentials expire and must be reissued with a fresh purpose.',
  },
  {
    key: 'data.incident.reportWindowHours',
    group: 'data',
    label: 'Cyber incident reporting window',
    value: 6,
    unit: 'hours from detection',
    citation: 'CERTIN-2022-DIR',
    effectiveFrom: '2022-06-28',
    changedBy: 'Statute',
    note: 'Drives the incident resolution clock on every pilot.',
  },
  {
    key: 'procurement.readiness.recommendThreshold',
    group: 'procurement',
    label: 'Procurement readiness recommendation threshold',
    value: 75,
    unit: 'points of 100',
    citation: 'PRAYOG-SOP-12',
    effectiveFrom: '2026-01-01',
    changedBy: 'PMU · A. Deshmukh',
    note: 'Advisory only. The written pathway justification is the decision.',
  },
  {
    key: 'procurement.vfm.minSavingPercent',
    group: 'procurement',
    label: 'Minimum demonstrated value for money',
    value: 12,
    unit: 'percent against the closest market alternative',
    citation: 'PRAYOG-SOP-12',
    effectiveFrom: '2026-01-01',
    changedBy: 'Finance · K. Iyer',
    note: 'Below this, the pathway note must argue non-price grounds.',
  },
] as const;

const index = new Map(CONFIG_PARAMETERS.map((p) => [p.key, p]));

/** Read a configured value. Throws loudly if a component invents a key. */
export function policy<T extends string | number | boolean = number>(key: string): T {
  const param = index.get(key);
  if (!param) throw new Error(`Unknown configuration key: ${key}`);
  return param.value as T;
}

export function policyParam(key: string): ConfigParameter {
  const param = index.get(key);
  if (!param) throw new Error(`Unknown configuration key: ${key}`);
  return param;
}

export function policyNumber(key: string): number {
  return policy<number>(key);
}
